### PR TITLE
Update zimmering24a.pdf

### PR DESCRIPTION
**Pull request by zimmer-ing**
Updated zimmering24a.pdf as some figures (1-6) and tables (2,4,5) had to be updated due to a minor bug in the experiments. Major things in the paper, including its central statements and contributions have not been changed.

### CODE REVIEW

**Comment by zimmer-ing** [comment]
Dear PMLR Editors,

im am one of the editors if this volume (Bernd Zimmering). I needed to update zimmering24a.pdf as some of the figures and tables had to be updated, due to a minor bug in the experiments. Please see my commit for more details.

Kind Regards,
Bernd

**Comment by lawrennd** [comment]
Hi Bernd, I need confirmation from the proceedings editors before accepting changes to a PDF. Can you provide confirmation ?

**Comment by CeciliaCoelho** [comment]
Dear @lawrennd we confirm these changes. Just sent an email to you. Thanks

**Comment by lawrennd** [comment]
Apologies for the delay in accepting, a busy couple of weeks of teaching!

**Pull request merged**
